version: '3'
services:
  app:
    build: app
    volumes:
      - ./app:/app
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
  nginx:
    build: nginx
    volumes:
      - ./app:/app
      - ./nginx/ssl:/etc/nginx/ssl
    ports:
      - 443:443
    depends_on:
      - app
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password #mysql -version:8対策
    env_file:
      - ./mysql/db.env
    volumes:
      - ./mysql/mysql:/var/lib/mysql